export const GET_TASK_LOADING = "GET_TASK_LOADING";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASK_FAILURE = "GET_TASK_FAILURE";
export const GET_TAG_LOADING = "GET_TAG_LOADING";
export const GET_TAG_SUCCESS = "GET_TAG_SUCCESS";
export const GET_TAG_FAILURE = "GET_TAG_FAILURE";



// export const ADD_TASK_TODO = "ADD_TASK_TODO";
// export const ADD_TASK_PROGRESS = "ADD_TASK_PROGRESS";
// export const ADD_TASK_COMPLETED = "ADD_TASK_COMPLETED";
